PROGRAM PRIME
  INTEGER N, I, ISPRIME
  N = 7
  ISPRIME = 1
  DO 10 I = 2, N-1
    IF (MOD(N, I) .EQ. 0) THEN
      ISPRIME = 0
    ENDIF
10 CONTINUE
  IF (ISPRIME) THEN
    PRINT *, 'PRIME'
  ELSE
    PRINT *, 'COMPOSITE'
  ENDIF
END
